spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username:  ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update #update
    show-sql: true

    logging:
      level:
        org.hibernate.SQL: DEBUG
        org.hibernate.type.descriptor.sql.BasicBinder: TRACE

  jackson:
    property-naming-strategy: SNAKE_CASE

redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}

jwt:
  header: ${JWT_HEADER:Authorization}
  prefix: ${JWT_PREFIX:Bearer }
  secret_key: ${JWT_SECRET:asdf}
  access_exp: ${TOKEN_ACCESS_EXP:60000}
  refresh_exp: ${TOKEN_REFRESH_EXP:120960}

cloud:
  aws:
    credentials:
      accessKey:
      secretKey:
    s3:
      bucket: demu-s3-bucket
    region:
      static: ap-northeast-2

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL:jeaminruy@gmail.com}
    password: ${PASSWORD:cuth uyaz tggw qkhf}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
